baseURL = "https://example.com/"
languageCode = "en-US"
title = "Igor Shalimov's Personal Website"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profile.jpg"
  author = "Igor Shalimov"
  description = "Personal website of Software Engineer Igor Shalimo"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "shalimov"
  Email         = "work.igor.shalimov@gmail.com"
#   Twitter       = "username"
  LinkedIn      = "jshero"
#   Stackoverflow = "username"
#   Medium        = "username"
#   Telegram      = "igor"
  RSS           = "/blog/index.xml"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
